import { useContext, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import '../App.css';
import AppContext from '../context/appContext';

// ADD UNIQUE CODE LINKED TO PATCH TO FORM

function Intro() {
  const [title, setTitle] = useState('');
  const [yoe, setYoe] = useState(0);
  const [pyoe, setPyoe] = useState(0);
  const [instanceIdField, setInstanceIdField] = useState('');
  const navigate = useNavigate();
  const appContext = useContext(AppContext);
  const { instanceId, setDetails } = appContext;

  const handleSubmit = event => {
    event.preventDefault();
    console.log(`${title} ${yoe} ${pyoe}`);
    setDetails(title, yoe, pyoe, instanceIdField);
  };

  useEffect(() => {
    // navigate once the users details have been set
    if (instanceId !== '') {
      navigate('/vote');
    }
  }, [instanceId]);

  return (
    <>
      <h1>Welcome 👋</h1>
      <p>
        First off, thank you very much for agreeing to participate in this
        study! We deeply appreciate your contributions to our research, and will
        reach out to you again once the research paper is published!
        <br />
        <br />
        This website will present you with pairs of explanations for a given
        patch, and your job is to select which one you feel more accurately
        describes the changes (as in, which explanation you would find more
        helpful if you saw this patch in your repository). Please note that
        these explanations have been generated by LLMs, and thus may contain
        hallucinated content which may influence whether you prefer an
        explanation over another.
      </p>
      <p>
        Before you start, please enter your current title, years of programming
        experience, and years of python experience.
      </p>
      <form onSubmit={handleSubmit}>
        <label>
          Job title (i.e. Undergraduate Student, Postraguate Student, Software
          Developer, Software Engineer, etc.):
        </label>
        <br />
        <input
          type='text'
          value={title}
          onChange={e => setTitle(e.target.value)}
        />
        <br />
        <br />
        <label>Years of programming experience:</label>
        <br />
        <input
          type='number'
          value={yoe}
          onChange={e => setYoe(e.target.value)}
        />
        <br />
        <br />
        <label>Years of python programming experience:</label>
        <br />
        <input
          type='number'
          value={pyoe}
          onChange={e => setPyoe(e.target.value)}
        />
        <br />
        <p>
          Inside the email you received inviting you to this website, you will
          find your randomly-assigned patch ID for which you will compare patch
          explanations. Please enter your patch ID (as-is, with no additional
          formatting) and press submit to continue. (e.g.
          astropy__astropy-12907, django__django-11141)
        </p>
        <label>Instance ID:</label>
        <br />
        <input
          type='text'
          value={instanceIdField}
          onChange={e => setInstanceIdField(e.target.value)}
        />
        <br />
        <br />
        <input className='btn' type='submit' value='Submit' />
      </form>
    </>
  );
}

export default Intro;
